version: '3.9'
services:
    nestjs:
        build: .
        ports:
            - '3000:3000'
        links:
            - 'redis:redis'
        depends_on:
            - db
        networks:
            - test
        environment:
            - REDIS_HOST=redis
            - DATABASE_HOST=postgres-db
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redisdata:/data'
    db:
        image: postgres
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_DATABASE}
        ports:
            - '5432:5432'
        volumes:
            - 'dbdata:/var/lib/postgres/data'
        container_name: postgres-db
        networks:
            - test
    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - '8081:8081'
volumes:
    dbdata:
    redisdata:
networks:
    test:
