version: '3.9'
services:
    web:
        build: .
        ports:
            - '3000:3000'
        links:
            - 'redis:redis'
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redisdata:/data'
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: dels
        ports:
            - '5432:5432'
        volumes:
            - 'dbdata:/var/lib/postgres/data'

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - '8081:8081'
volumes:
    dbdata:
    redisdata:
