version: '3.9'
services:
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redisdata:/data'
    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - '8081:8081'
    nestjs:
        build: .
        ports:
            - '3000:3000'
        links:
            - 'redis:redis'
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
volumes:
    redisdata:
        driver: local
networks:
    test:
